services:
  _defaults:
    autowire: true
    public: false

  ###############################################
  ## Jobs
  ###############################################
  # Invoicer
  Ivoz\Provider\Infrastructure\Redis\Jobs\Invoicer:
    arguments:
      $redisDb: '%redis_jobs_db%'

  Ivoz\Provider\Domain\Job\InvoicerJobInterface:
    alias: Ivoz\Provider\Infrastructure\Redis\Jobs\Invoicer

  # Cgrates reload
  Ivoz\Cgr\Infrastructure\Gearman\Jobs\Cgrates:
    arguments:
      $redisDb: '%redis_jobs_db%'

  Ivoz\Cgr\Domain\Job\RaterReloadInterface:
    alias: Ivoz\Cgr\Infrastructure\Gearman\Jobs\Cgrates

  # Rates importer
  Ivoz\Provider\Infrastructure\Gearman\Jobs\RatesImporter:
    arguments:
      $redisDb: '%redis_jobs_db%'

  Ivoz\Provider\Domain\Job\RatesImporterJobInterface:
    alias: Ivoz\Provider\Infrastructure\Gearman\Jobs\RatesImporter

  # Audio Recoder
  Ivoz\Provider\Infrastructure\Gearman\Jobs\Recoder:
    arguments:
      $redisDb: '%redis_jobs_db%'

  Ivoz\Provider\Domain\Job\RecoderJobInterface:
    alias: Ivoz\Provider\Infrastructure\Gearman\Jobs\Recoder

  # Kamailio RPC calls
  Ivoz\Kam\Infrastructure\Redis\Job\TrunksRpcJob:
    arguments:
      $redisDb: '%redis_jobs_db%'

  Ivoz\Kam\Infrastructure\Redis\Job\UserRpcJob:
    arguments:
      $redisDb: '%redis_jobs_db%'
